<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <AssemblyName>ManagedSockets</AssemblyName>
        <RootNamespace>ManagedSockets</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="EventArgs" />
    </ItemGroup>

</Project>
